# Generated by Django 5.0.7 on 2024-07-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('memorandum', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=255)),
                ('work_order_type', models.CharField(max_length=50)),
                ('link_inspection', models.TextField()),
                ('link_work_order', models.TextField()),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('meter_reading', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
