# Generated by Django 5.1 on 2024-08-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('memorandum', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('asignado_a', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_orden_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('inspeccion_enlaces', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_trabajo_enlace', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_vehiculo', models.CharField(max_length=50)),
                ('nombre_vehiculo', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('lectura_medidor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_trabajo_estimado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
