# Generated by Django 5.1 on 2024-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_vehiculo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('numero_chasis', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('numero_vin', models.CharField(blank=True, max_length=50)),
                ('placas', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('objetivo_utilizacion', models.TextField(blank=True)),
                ('estado_registro', models.CharField(blank=True, max_length=100)),
                ('fecha_exp_registro', models.DateField(blank=True, null=True)),
                ('nombre_operador', models.CharField(blank=True, max_length=100)),
                ('prioridad_mantenimiento', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('ubicacion_geografica', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
