# Generated by Django 5.0.7 on 2024-07-12 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('memorandum', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=255)),
                ('work_order_type', models.CharField(max_length=50)),
                ('link_inspection', models.TextField()),
                ('link_work_order', models.TextField()),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('meter_reading', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_material_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_wo_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosistemas_django.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosistemas_django.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='PartsMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50)),
                ('article_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('article_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosistemas_django.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('date', models.DateTimeField()),
                ('observer', models.CharField(max_length=255)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosistemas_django.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='LaborDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=255)),
                ('work_code', models.CharField(max_length=50)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosistemas_django.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file_path', models.TextField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosistemas_django.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_description', models.TextField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosistemas_django.workorder')),
            ],
        ),
    ]
